config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "users#select_user"
  # get "/new_boat_js" => "boats#new_boat_js"
  get "/check_status" => "jobs#check_status"
  post "/check_status" => "jobs#check_status"
  get "/search" => "jobs#index"
  get "/est_cost/" => "jobs#est_cost"
  get "/top_page/" => "airplanes#top_page"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :airports
  resources :jobs

  resources :airplanes
  resources :photos	# use this version if editing title, description, other db values

end

app/models/airplane.rb
class Airplane < ApplicationRecord
  belongs_to :user
  belongs_to :airport
  belongs_to :photo
  has_many :job_planes
  has_many :jobs, through: :job_planes
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:user_id, :airport_id, :photo_id, :plane_name, :capacity)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_with(model: airplane, local: true) do |form| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>
      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.label :plane_name, "Name of Plane: " %>
    <%= form.text_field :plane_name %> <br>
    <%= form.label :capacity, "Plane Capacity: " %>
    <%= form.number_field :capacity %>
    <span>(in kgs)</span> <br>
    <%= form.label :photo_id, "Select Photo: " %>
    <%= form.collection_select :photo_id, Photo.order(:title), :id, :title, include_blank: "Planes" %> <br>
    <%= form.label :airport_id, "Select Home Airport: " %>
    <%= form.collection_select :airport_id, Airport.order(:city_code), :id, :city_code, include_blank: "Airport" %> <br>
    <%= form.hidden_field :user_id, value: current_user[:id] %> <br>
    <%= form.submit "Submit" %>
  </div>
<% end %>
<br>

app/views/airplanes/edit.html.erb
<h2>Editing Airplane</h2>
<%= render 'form', airplane: @airplane %>
<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<h2>All Airplanes</h2>
<% if current_user %>
  <%= link_to 'Step: 1 Upload a Airplane Photo', new_photo_path, class: "button_link_to" %>
  <%= link_to 'Step 2: Add Airplane to Database', new_airplane_path, class: "button_link_to" %>
<% end %>
<br> <br>

<% @airplanes.each do |airplane| %>
  <% photo = Photo.find(airplane[:photo_id]) %>
  <div class="planeInfo">
    <h3 class="planeText"><%= airplane[:plane_name] %></h3> |
    <p class="planeText">Capacity: <%= airplane[:capacity] %> kgs </p> |
    <p class="planeText"><%= link_to 'Edit', edit_airplane_path(airplane), class: "link_to" %></p> |
    <p class="planeText"><%= link_to 'Delete', airplane, method: :delete, data: { confirm: 'Are you sure?' }, class: "link_to" %></p>
    <br>
    <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
  </div>
  <br>
<% end %>
<br>
<div>
  <%= link_to 'Top', "/top_page/", remote: true, class: "top_page" %>
</div>

app/views/airplanes/new.html.erb
<h2>New Airplane</h2>
<%= render 'form', airplane: @airplane %>
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<% photo = Photo.find(@airplane[:photo_id]) %>
<div>
  <h3><%= @airplane[:plane_name] %></h3> 
  <p>Capacity: <%= @airplane[:capacity] %> kgs </p>
  <br>
  <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
</div>
<br>
<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'All Airplanes', airplanes_path %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/top_page.js.erb
window.scrollTo(0, 0);