config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "users#select_user"
  # get "/new_boat_js" => "boats#new_boat_js"
  get "/check_status" => "jobs#check_status"
  post "/check_status" => "jobs#check_status"
  get "/search" => "jobs#index"
  get "/est_cost/" => "jobs#est_cost"
  get "/top_page/" => "airplanes#top_page"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :airports
  resources :jobs

  resources :airplanes
  resources :photos	# use this version if editing title, description, other db values

end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :jobs_as_origin, :class_name => 'Job', :foreign_key => 'origin_id'
    has_many :jobs_as_destination, :class_name => 'Job', :foreign_key => 'destination_id'
    has_many :airplanes
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  # GET /airports
  # GET /airports.json
  def index
    puts "*** airport index ***"
    @airports = Airport.all
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
    puts "*** airport show ***"
  end

  # GET /airports/new
  def new
    puts "*** airport new ***"
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
    puts "*** airport edit ***"
  end

  def top_page
    puts "*** top of page ***"
    respond_to do |format|
        format.js { render :top_page }
    end
  end

  # POST /airports
  # POST /airports.json
  def create
    puts "*** airport create ***"
    @airport = Airport.new(airport_params)
    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    puts "*** airport destroy ***"
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: 'Airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:city_code)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_with(model: airport, local: true) do |form| %>
  <% if airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>
      <ul>
      <% airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.label :city_code, "Airport City Code: " %>
    <%= form.text_field :city_code %>
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h2>Edit Airport</h2>
<%= render 'form', airport: @airport %>
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<h2>All Airports Partnering with On Fly</h2>
<%= link_to 'Add an Airport', new_airport_path, class: "button_link_to" %>
<br> <br>
<div class="tableDiv">
  <table>
    <thead>
      <tr>
        <th>Airport Code</th>
        <th>Edit Airport</th>
        <th>Delete Airport</th>
      </tr>
    </thead>
    <tbody>
      <% @airports.each do |airport| %>
        <tr>
          <td><%= airport[:city_code] %></td>
          <td><%= link_to 'Edit', edit_airport_path(airport), class: "link_to" %></td>
          <td><%= link_to 'Delete', airport_path(airport), method: :delete, data: { confirm: 'Are you sure?' }, class: "link_to" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/airports/new.html.erb
<h2>New Airport</h2>
<%= render 'form', airport: @airport %>
<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<h2><%= @airport[:city_code] %></h2>
<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>