config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "users#select_user"
  # get "/new_boat_js" => "boats#new_boat_js"
  get "/check_status" => "jobs#check_status"
  post "/check_status" => "jobs#check_status"
  get "/search" => "jobs#index"
  get "/est_cost/" => "jobs#est_cost"
  get "/top_page/" => "airplanes#top_page"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :airports
  resources :jobs

  resources :airplanes
  resources :photos	# use this version if editing title, description, other db values

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviceProject</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- not logged in  -->
    <ul id="nav">
      <% if !current_user %>
        <li class="navigation"><%= link_to "Home", home_path %></li>
        <li class="navigation"><%= link_to "Employee Sign in", new_user_session_path %></li>
        <li class="navigation"><%= link_to 'Create New Order', new_job_path %></li>
        <li class="navigation"><%= link_to 'Check Status', check_status_path %></li>
      <% else %>
        <li class="navigation"><%= link_to "Main Page", home_path %></li>
        <li class="navigation"><%= link_to 'Create New Order', new_job_path %></li>
        <li class="navigation"><%= link_to "All Orders", jobs_path %></li>
        <li class="navigation"><%= link_to 'View/Create New Airport', airports_path %></li>
        <li class="navigation"><%= link_to "View/Create New Airplane", airplanes_path %></li>
        <li class="navigation"><%= link_to "All Employees", users_path %></li>
        <li class="navigation"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <div id="c_user_email">Currently Signed In: <%= current_user.email %></div>
      <% end %>
    </ul>
    <div class="section">
      <p class="notice"><%= notice %></p>
      <%= yield %>
    </div>
 	<footer class="section">
    <hr>
    <p>Questions about your order? Contact SO FLY at sofly@email.com or (202) 123-4567</p>
    <p> &copy; 2017 So Fly</p>
    <!-- HTML usually doesn't recognize symbols like a copyright sign, so there is special syntax to use -->
  </footer>
  </body>
</html>